routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['auth:web']], function () {
    // Route::get('/1111', 'PostController@guard');  
    Route::post('/post.user', 'PostController@user')->name('post.user');
    Route::resource('post', 'PostController');
    Route::resource('message','MessageController');
  
    // Route::get('/post', 'MessageController@create');
    // Route::get('/post','MessageController@index');
});

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\MeRepository;

class MessageController extends Controller
{
    protected $messages;

    public function __construct(MeRepository $messages)
    {
        $this->messages = $messages;
    }

    public function index()
    {
        $posts = $this->messages->index();
        
        return view('post.show', ['messages' => $posts]);
    }

    public function create()
    {
        return view('post.show');
    }   

    public function store(Request $request)
    {
        
      
        $post = $this->messages->create(request()->only('post_id', 'content'));
        if ($post) {
            return redirect()->route('post.show', $post->post_id);
        }
    
        return back();
    }

    public function update(Request $request, $id)
    {
        // $result = $this->postRepo->update($id, request()->only('user_id', 'content'));

        // if (!$result) {
        // return redirect()->route('post.index');
        // }

        // return redirect()->route('post.show', $id);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\PostRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Entities\Post;
use App\Entities\Message;
class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    protected $postRepo;

    public function __construct(PostRepository $postRepo)
    {
        $this->postRepo = $postRepo;
    }
    
    

    public function index()
    {
        $posts = $this->postRepo->index();
        // dd($posts);
      
        return view('post.index', ['posts' => $posts]);
    }

    public function user()
    {
        
        $posts = $this->postRepo->user(request()->content);
        // dd($posts);
        
        return view('post.index', ['posts' => $posts]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = $this->postRepo->create(request()->only('title', 'content'));
    
        if ($post) {
        return redirect()->route('post.show', $post->id);
        }
    
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = $this->postRepo->find($id);
        $message = Message::with('user')->where('post_id',$id)->get();
        
        if (!$post) {
            return redirect()->route('post.index');
        }
        
        return view('post.show', ['post' => $post , 'messages' => $message] );
    }
    // 'message' => $message
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    
    public function edit($id)
    {
        $post = $this->postRepo->find($id);

        if (!$post) {
            return redirect()->route('post.index');
        }
    
        return view('post.edit', ['post' => $post]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $result = $this->postRepo->update($id, request()->only('title', 'content'));

        if (!$result) {
        return redirect()->route('post.index');
        }

        return redirect()->route('post.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->postRepo->delete($id);
    
        if ($result) {
        return redirect()->route('post.index');
        }
    
        return back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                    <a href="./post">前往網站</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/post/create.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <form action="{{ route('post.store') }}" method="POST">
            @csrf
            <div class="form-group row">
                <label for="title" class="col-sm-1 col-form-label">標題</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="title" name="title" placeholder="標題">
                </div>
            </div>
            <div class="form-group row">
                <label for="content" class="col-sm-1 col-form-label">內容</label>
                <div class="col-sm-4">
                    <textarea class="form-control" id="content" name="content">
                    </textarea>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" class="btn btn-primary" value="送出">
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <form action="{{ route('post.update', $post->id) }}" method="POST">
            @csrf
            @method('PUT')
            
            <div class="form-group row">
                <label for="title" class="col-sm-1 col-form-label">標題</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" id="title" name="title" value="{{ $post->title }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="content" class="col-sm-1 col-form-label">內容</label>
                <div class="col-sm-4">
                    <textarea class="form-control" id="content" name="content">{{ $post->content }}</textarea>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="submit" class="btn btn-primary" value="送出">
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">
        <div align="center">
            <form action="{{ route('post.user') }}" method="post">
                @csrf
                <textarea style="width:600px; height:30px;" class="form-control" id="content" name="content">
                </textarea>
                <input type="submit" value="我要搜尋la">
            </form>
        </div>
        <div>
            &nbsp
        </div>
        <div align="center">
            <a href="{{ route('post.create') }}" class="btn btn-primary">我要貼文</a>
        </div>
        {{-- <a href="{{ route('post.user') }}" class="btn btn-secondary">111</a> --}}

        @foreach ($posts as $key => $post)
        
            <div class="card text-center">
                <div class="card-header">
                    標題：{{ $post->title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        作者：{{ $post->user->name }}
                    </h5>
                    <a href="{{ route('post.show', $post->id) }}" class="btn btn-secondary">查看文章</a>
                </div>
                <div class="card-footer text-muted">
                    發文日期：{{ $post->created_at }}
                </div>
            </div><br>
        @endforeach
    {!! $posts->links() !!}
@endsection

resources/views/post/show.blade.php
@extends('layouts.app') 

@section('content')
    <div class="container">      
        <div class="card text-center">
            <div class="card-header">
           
                標題：{{ $post->title }}
            </div>
            
            <div class="card-body">
                <h5 class="card-title">
                    作者：{{ $post->user->name }}
                </h5>
                <p class="card-text">
                    {{ $post->content }}
               
                </p>
            </div>
            <div class="card-footer text-muted">
                發文日期：{{ $post->created_at }}
            </div>
            @if (auth()->user()->name == $post->user->name)
            
             <div align="center">
                <a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary">編輯</a>

                <form action="{{$post->id}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger">刪除</button>
                </form>
            </div>   
            
            @else 
                <div align="center">
                <!-- <a href="{{ route('post.edit', $post->id) }}" class="btn btn-primary">編輯</a> -->

                <form action="{{ route('post.destroy', $post->id) }}" method="POST">
                    @csrf
                    @method('DELETE')
                    <!-- <button class="btn btn-danger">刪除</button> -->
                </form>
            </div>
            
            @endif
            
        @foreach ($messages as $key => $message)
            <div class="card-footer text-muted">
                   
                    發文者：{{ $message->user->name  }}發文日期：{{ $message->created_at }}
            </div>
                <div >
                       
                    <div>
                        {{$message->content}}
                    </div>
                    
                </div>
           
        @endforeach
            <div class="card-footer text-muted">
                <div style='display:none;'><input type="text" id="user_id" name="user_id"></div>
                發文者：{{ auth()->user()->name }}
            </div>
            <div >
                <form action="{{ route('message.store') }}" method="post">
                @csrf
                <div class="col-sm-4">
                <input type="hidden" name="post_id" value="{{$post->id}}">
                    <textarea style="width:1050px; height:200px;" class="form-control" id="content" name="content">
                    </textarea>
                </div>
                <button class="btn btn-primary">送出</button>
                <button class="btn btn-danger">刪除</button>
                <a href="./">返回</a>
                </form> 
            </div>
        </div>
    </div>
@endsection